# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Build and Deploy Spring-based Identity Provider

on:
  push:
    branches:
      - main

env:
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  SSH_PORT: 22

  SSH_PASS: ${{ secrets.SSH_PRIVATE_KEY }}
  SSH_HOST: ${{ secrets.SSH_HOST }}
  SSH_USER: ${{ secrets.SSH_USER }}
  CONTAINER_NAME: identityproviderapi
  IMAGE_NAME: ${{ secrets.DOCKER_USERNAME }}/identity-provider-api

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 23
        uses: actions/setup-java@v3
        with:
          java-version: '23'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn clean package

      - name: Build & push Docker image
        run: |
          echo '${{ env.DOCKER_PASSWORD }}' | docker login -u ${{ env.DOCKER_USERNAME }} --password-stdin
          docker buildx create --use --name workflowBuilder
          docker buildx build --no-cache --platform=linux/amd64,linux/arm64 -t ${{ env.IMAGE_NAME }} --push .
          docker logout
  deploy_dev:
    runs-on: ubuntu-latest
    needs: build
    environment: development
    steps:
      - name: Setup SSH keys
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Remote ssh to server and update cloud server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          port: ${{ env.SSH_PORT }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script_stop: true
          script: |
            if docker ps -a --format '{{.Names}}' | grep -q ${{ env.CONTAINER_NAME }}; then
              echo "Check 1"
              docker stop ${{ env.CONTAINER_NAME }}
              docker rm ${{ env.CONTAINER_NAME }}
            fi
            docker pull --quiet ${{ env.IMAGE_NAME }}
            if [ $? -eq 0 ]; then
              echo "Docker image ${{ env.IMAGE_NAME }} pulled successfully"
            else
              echo "Error: Failed to pull Docker image ${{ env.IMAGE_NAME }}"
              exit 1
            fi

            docker run -d \
              --name ${{ env.CONTAINER_NAME }} \
              -p 8091:8091 \
              ${{ env.IMAGE_NAME }}

            docker logout
            sleep 10
